### PR TITLE
Backend basic (without database)

### PR DESCRIPTION
**Pull request by longfeiCA**
This update includes all basic java classes used for this project. I tried to complete this as quickly as possible, so that everybody has an idea how the backend works. 

To-do List: 
1. Database Integration
2. Picture encoding and decoding
3. Write tests for these classes
4. Add user to userList after user creation (check device)
5. QR code and hash code generation

Please review the code and post your comments, thank you!

### CODE REVIEW

**Comment by StevenYang23** [comment]
looks good to me

**Comment by longfeiCA** [comment]
All the buttons except "Check Device" on the first page should be implemented. Let me know if you find anything that is unclear or has not been implemented.

**Review by plzhn — APPROVED** [review]
okay

**Review by reubenjosephjohn — APPROVED** [review]
looks fine to me

**Review by StevenYang23 — APPROVED** [review]

**Pull request merged**
